name: CustomEconomy
version: '1.0.1'
main: me.gypopo.economy.CustomEconomy
description: A non persistent economy provider using the ESGUI API
api-version: '1.19'
folia-supported: true
dependencies:
  server:
    EconomyShopGUI-Premium:
      load: AFTER